name: C++ MSBuild CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    strategy:
      matrix:
        # 定义构建配置，可以同时测试不同的组合
        configuration: [Release]
        platform: [x64, x86]

    steps:
      - name: 检出代码
        uses: actions/checkout@v6

      - name: 添加 MSBuild 到环境变量
        uses: microsoft/setup-msbuild@v2

      - name: 安装 NuGet
        uses: NuGet/setup-nuget@v2

      - name: 重建 NuGet 包
        run: nuget restore StarlightGUI.sln

      - name: 生成构建版
        run: |
          msbuild StarlightGUI.sln `
          /p:Configuration=Release `
          /p:Platform=x64 `
          /p:AppxPackageSigningEnabled=false `
          /p:AppxBundle=Never `
          /p:UapAppxPackageBuildMode=SideloadOnly

      - name: 复制构建版
        run: |
          mkdir publish
          copy x64\Release\StarlightGUI\StarlightGUI.exe publish\

      - name: 压缩构建版
        run: Compress-Archive -Path publish\* -DestinationPath StarlightGUI-Win-x64.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: StarlightGUI-Win-x64.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}